create table if not exists orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  name text,
  phone text,
  address text,
  notes text,
  items jsonb not null,
  total_price numeric not null,
  payment_status text not null default 'pending',
  stripe_session_id text
);

alter table orders enable row level security;

-- Public read (so admin.html z anon key może pobrać listę)
create policy if not exists "public_read_orders" on orders for select using (true);

-- Insert/update by service role via Netlify Functions (service role bypasses RLS).